version: '3'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_URI: mariadb://you:should@hire-me/nodejs-developer
    volumes:
      - ./src:/app/src # hot reload, babe
    networks:
      - hire-me
    depends_on:
      - hire-me
  
  hire-me:
    image: mariadb
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: nodejs-developer
      MYSQL_USER: you
      MYSQL_PASSWORD: should
    networks:
      - hire-me

networks:
  hire-me:
